controller_list:
  - name: arm_controller
    action_ns:  follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
    - joint1
    - joint2
    - joint3
    - joint4
  
  - name: gripper_controller
    action_ns:  follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
    - gripper